<?php

namespace Proxies\__CG__\Pidev\ReaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \Pidev\ReaBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'cin', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'mail', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'nomutilisateur', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'motpasse', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'role', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'datecreation', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'datemodification', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'numtel', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'idagence4');
        }

        return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'cin', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'mail', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'nomutilisateur', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'motpasse', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'role', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'datecreation', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'datemodification', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'numtel', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Utilisateur' . "\0" . 'idagence4');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', array($cin));

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', array());

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomutilisateur($nomutilisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomutilisateur', array($nomutilisateur));

        return parent::setNomutilisateur($nomutilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomutilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomutilisateur', array());

        return parent::getNomutilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotpasse($motpasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotpasse', array($motpasse));

        return parent::setMotpasse($motpasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotpasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotpasse', array());

        return parent::getMotpasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', array($datecreation));

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', array());

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodification($datemodification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodification', array($datemodification));

        return parent::setDatemodification($datemodification);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodification', array());

        return parent::getDatemodification();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumtel($numtel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumtel', array($numtel));

        return parent::setNumtel($numtel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumtel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumtel', array());

        return parent::getNumtel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdagence4(\Pidev\ReaBundle\Entity\Agence $idagence4 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdagence4', array($idagence4));

        return parent::setIdagence4($idagence4);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdagence4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdagence4', array());

        return parent::getIdagence4();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
