<?php

namespace Proxies\__CG__\Pidev\ReaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Demandeimmeuble extends \Pidev\ReaBundle\Entity\Demandeimmeuble implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Demandeimmeuble' . "\0" . 'nbretage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Demandeimmeuble' . "\0" . 'nbrappartement', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Demandeimmeuble' . "\0" . 'iddemande');
        }

        return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Demandeimmeuble' . "\0" . 'nbretage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Demandeimmeuble' . "\0" . 'nbrappartement', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Demandeimmeuble' . "\0" . 'iddemande');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Demandeimmeuble $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNbretage($nbretage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbretage', array($nbretage));

        return parent::setNbretage($nbretage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbretage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbretage', array());

        return parent::getNbretage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrappartement($nbrappartement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrappartement', array($nbrappartement));

        return parent::setNbrappartement($nbrappartement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrappartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrappartement', array());

        return parent::getNbrappartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIddemande(\Pidev\ReaBundle\Entity\Demande $iddemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIddemande', array($iddemande));

        return parent::setIddemande($iddemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getIddemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddemande', array());

        return parent::getIddemande();
    }

}
