<?php

namespace Proxies\__CG__\Pidev\ReaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Maison extends \Pidev\ReaBundle\Entity\Maison implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrchambre', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrsalledebain', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrcuisine', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrsallon', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrsuite', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbretage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'surfacehabitale', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'terrasse', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'picine', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'garage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'balcon', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'meuble', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'chauffage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'climatisation', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'parking', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'idoffre');
        }

        return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrchambre', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrsalledebain', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrcuisine', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrsallon', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbrsuite', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'nbretage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'surfacehabitale', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'terrasse', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'picine', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'garage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'balcon', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'meuble', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'chauffage', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'climatisation', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'parking', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Maison' . "\0" . 'idoffre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Maison $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNbrchambre($nbrchambre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrchambre', array($nbrchambre));

        return parent::setNbrchambre($nbrchambre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrchambre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrchambre', array());

        return parent::getNbrchambre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrsalledebain($nbrsalledebain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrsalledebain', array($nbrsalledebain));

        return parent::setNbrsalledebain($nbrsalledebain);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrsalledebain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrsalledebain', array());

        return parent::getNbrsalledebain();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrcuisine($nbrcuisine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrcuisine', array($nbrcuisine));

        return parent::setNbrcuisine($nbrcuisine);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrcuisine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrcuisine', array());

        return parent::getNbrcuisine();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrsallon($nbrsallon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrsallon', array($nbrsallon));

        return parent::setNbrsallon($nbrsallon);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrsallon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrsallon', array());

        return parent::getNbrsallon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrsuite($nbrsuite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrsuite', array($nbrsuite));

        return parent::setNbrsuite($nbrsuite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrsuite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrsuite', array());

        return parent::getNbrsuite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbretage($nbretage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbretage', array($nbretage));

        return parent::setNbretage($nbretage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbretage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbretage', array());

        return parent::getNbretage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurfacehabitale($surfacehabitale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurfacehabitale', array($surfacehabitale));

        return parent::setSurfacehabitale($surfacehabitale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurfacehabitale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurfacehabitale', array());

        return parent::getSurfacehabitale();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerrasse($terrasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerrasse', array($terrasse));

        return parent::setTerrasse($terrasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerrasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerrasse', array());

        return parent::getTerrasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicine($picine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicine', array($picine));

        return parent::setPicine($picine);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicine', array());

        return parent::getPicine();
    }

    /**
     * {@inheritDoc}
     */
    public function setGarage($garage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGarage', array($garage));

        return parent::setGarage($garage);
    }

    /**
     * {@inheritDoc}
     */
    public function getGarage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGarage', array());

        return parent::getGarage();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalcon($balcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalcon', array($balcon));

        return parent::setBalcon($balcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalcon', array());

        return parent::getBalcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeuble($meuble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeuble', array($meuble));

        return parent::setMeuble($meuble);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeuble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeuble', array());

        return parent::getMeuble();
    }

    /**
     * {@inheritDoc}
     */
    public function setChauffage($chauffage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChauffage', array($chauffage));

        return parent::setChauffage($chauffage);
    }

    /**
     * {@inheritDoc}
     */
    public function getChauffage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChauffage', array());

        return parent::getChauffage();
    }

    /**
     * {@inheritDoc}
     */
    public function setClimatisation($climatisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClimatisation', array($climatisation));

        return parent::setClimatisation($climatisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getClimatisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClimatisation', array());

        return parent::getClimatisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setParking($parking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParking', array($parking));

        return parent::setParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function getParking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParking', array());

        return parent::getParking();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoffre(\Pidev\ReaBundle\Entity\Offre $idoffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoffre', array($idoffre));

        return parent::setIdoffre($idoffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoffre', array());

        return parent::getIdoffre();
    }

}
