<?php

namespace Proxies\__CG__\Pidev\ReaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Operation extends \Pidev\ReaBundle\Entity\Operation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'numcontrat', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'dateoperation', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'nature', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'idrdv');
        }

        return array('__isInitialized__', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'numcontrat', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'dateoperation', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'nature', '' . "\0" . 'Pidev\\ReaBundle\\Entity\\Operation' . "\0" . 'idrdv');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Operation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumcontrat()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNumcontrat();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcontrat', array());

        return parent::getNumcontrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateoperation($dateoperation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateoperation', array($dateoperation));

        return parent::setDateoperation($dateoperation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateoperation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateoperation', array());

        return parent::getDateoperation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature($nature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', array($nature));

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', array());

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrdv(\Pidev\ReaBundle\Entity\Rendezvous $idrdv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrdv', array($idrdv));

        return parent::setIdrdv($idrdv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrdv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrdv', array());

        return parent::getIdrdv();
    }

}
